name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
      - name: Install dependencies and build
        run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o publish
      - name: Create zip file
        run: |
          Compress-Archive -Path publish\* -DestinationPath app.zip
        shell: pwsh
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automated release of BetterPerfMon for version ${{ github.ref_name }}."
          draft: false
          prerelease: false
      - name: Upload Build Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app.zip
          asset_name: app.zip
          asset_content_type: application/zip
